### ISSUE TITLE
Create DeRegisterZafiraCredentials

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/jenkins-master#148]
Create a new DeRegisterZafiraCredentials job in ManagmentJobs
This job must delete Zafira credentials for definite organisation

This job purpose is to delete Zafira credentials in case if organisation wants to disable Zafira integration, but still wants to use qps-pipelines

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/237/files

**Comment by vdelendik** [comment]
closing as won't fix. it is easier to remove organization at all to achieve similar results
