### ISSUE TITLE
Update Readme:Need to restart Jenkins after update github auth token in Jenkins

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#219]
Test case:
1. Updade credentials in Jenkins
2. Restart Jenkins
3. Open/Close Pull request in Github or create a new PL
- Verify that Pull request jobs are executed

**Comment by okamara** [comment]
Added new case "Need to restart Jenkins after update Github Personal access token" here https://github.com/qaprosoft/qps-infra/blob/master/docs/config-guide.md

**Comment by vdelendik** [comment]
refactored and verified on prod docs site: https://zebrunner.github.io/zebrunner/config-guide/#set-up-github-pull-request-builder
