### ISSUE TITLE
Scanner is not working properly in Zafira

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#249]
Tested: jenkins-master: 5.1-beta1,qps-infra- develop, pipeline- develop
Zafira: ui: 1.3.0; server: 1.3.1

Steps:
1. Scan Repo via Zafira Launcher
Actual result: Scan is endless and 400 error is present in log

<img width="1438" alt="Screen Shot 2020-06-11 at 7 24 58 PM" src="https://user-images.githubusercontent.com/32964663/84413626-93ad7600-ac19-11ea-9cd0-108dc16b8850.png">

**Comment by vdelendik** [comment]
in zebrunner (community edition) 1.0 launchers created successfully but modal message is not closed!

**Comment by okamara** [comment]
I still repro this issue on 1.0 (5.2-qps),reporting 1.9
@vdelendik what build I can use for testing this ticket?

**Comment by vdelendik** [comment]
fix is delivered into the develop branch.
Major note: we've fixed only hanging behavior. In reality it still can't be executed successfully.
So please verify that we got "back to list" message with error. If correct - close this one and submit a new functional defect

**Comment by okamara** [comment]
Issue is not fixed. Tested on develop branch

**Comment by vdelendik** [comment]
fix delivered in reporting-ui:1.13.0.68-SNAPSHOT

**Comment by dhreben** [comment]
Tested in reporting-ui:1.13.0.68-SNAPSHOT
Fixed.
