### ISSUE TITLE
update reportingServiceUrl parameter for RegisterOrganization

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#261]
INFRA_HOST url is reporting url as of now. it seems like we can test default value like:
http://${INFRA_HOST}

related ticket: https://github.com/qaprosoft/qps-pipeline/issues/863

**Comment by vdelendik** [comment]
fixed. in new RegisterOrganization job default values for service url and token are empty!

**Comment by okamara** [comment]
Verified on release version 5.2
