### ISSUE TITLE
Update jenkins to the newest version

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/jenkins-master#270]

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/jenkins-master/pull/273

**Comment by ilya-varchenya** [comment]
Test scenario:
Check jenkins version must be 2.254 and all plugins must be up to date

**Comment by dhreben** [comment]
**Verified.** 
Jenkins  V.2.254
<img width="1074" alt="Screen Shot 2020-08-28 at 11 40 25" src="https://user-images.githubusercontent.com/50950954/91540333-50fb6000-e923-11ea-939e-59b65addf4f9.png">
