### ISSUE TITLE
github pull request settings shoudn't be updated on jenkins restart

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#276]
GitHub Server API URL always is updated to cloud https://api.github.com after each restart.
piece of code which set this block shouldn't be executed if global env JENKINS_SECURITY_INITIALIZED=true

**Comment by ilya-varchenya** [comment]
PR into **develop**: https://github.com/zebrunner/jenkins-master/pull/277
PR into **master**: https://github.com/zebrunner/jenkins-master/pull/278

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Go into your jenkins-master
2. Open Jenkins -> Manage Jenkins -> Configure System
3. Find and check `JENKINS_SECURITY_INITIALIZED = true`
![image](https://user-images.githubusercontent.com/44428408/91838045-8ec6f400-ec55-11ea-832e-4a6729d494d0.png)
4. Change value of _GitHub Server API URL_ to anything:
![image](https://user-images.githubusercontent.com/44428408/91838182-c33ab000-ec55-11ea-9bb9-77f188b73aa0.png)
5. Save updates
6. Open Jenkins -> Manage Jenkins -> Script Console
7. Paste [this](https://github.com/zebrunner/jenkins-master/blob/master/manual_deployment/setup_ghprbhook_credentials.groovy) file into Script Console
8. Press run
9. Go to Jenkins -> Manage Jenkins -> Configure System
10. Check that your edited _GitHub Server API URL_ **hasn't been changed** to default (https://api.github.com)
11. Open Jenkins -> Manage Jenkins -> Configure System
12. Find and edit (or even delete) `JENKINS_SECURITY_INITIALIZED` value
13. Do steps from 4 to 9
15. Check that your edited _GitHub Server API URL_ **has been changed** to default (https://api.github.com)

**Comment by ilya-varchenya** [comment]
I'll check it myself

**Comment by dhreben** [comment]
Verified.
