### ISSUE TITLE
generate default RegisterRepository and launcher jobs in the root

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#292]
RegisterRepository and launcher jobs should be placed in the jenkins root to setup fully automatic reporting <-> ci intergation for launchers/scanners.
Old approach to generate such jobs inside organization folder should be saved as well..

**Comment by vdelendik** [comment]
done. RegisterRepository and launcher jobs should appear automatically after setup now suing zebrunner (branch: develop)

**Comment by okamara** [comment]
Verified on dev. Fixed.
