### ISSUE TITLE
integrate new Zebrunner-CE pipeline library by default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#296]
Ideally in scope of the ticket develop upgrade script as well to make it automatically.
for details visit: https://github.com/zebrunner/pipeline-ce/issues/2

P.S. all default management jobs should be updated as well

**Comment by vdelendik** [comment]
done. changes are pushed into zebrunner/jenkins-master:1.2-beta1 docker image.
this image is inetrgated into zebrunner/zebrunner (branch: develop)

**Comment by dhreben** [comment]
Verified.
