### ISSUE TITLE
setup valid groovy patcher on jenkins startup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#298]
1. reuse ZEBRUNNER_VERSION to identify current version
2. generate patch groovy scripts which can be applied/skipped baased on the currently detected version

for 1.2 release we have to patch a lot of management jobs plus global env variables

**Comment by vdelendik** [comment]
done. valid upgrade scenario is organized.

Testing scenario:
1. clone zebrunner from master, setup everything and run regression jobs
2. switched to develop branch and do recurive pull
3. execute upgrade task
`./zebrunner.sh upgrade`
4. restart everything
-> during restart jenkins-master should be upgraded to latest version. 

To test valid upgrade:
1. run old jobs -> all of them should be executed as earlier using qps_pipeline_branch/version and old qps-pipeline repo 
2. all Management_Jobs regenerated using versioned "Zebrunner-CE@1.1" library
![image](https://user-images.githubusercontent.com/4551455/97763847-eda5ce00-1b1d-11eb-9f5b-f8c23c224caf.png)
3. register organization and repo vs old jobs
-> all jobs are recreated. In all of them also versioned "Zebrunner-CE@1.1" pipeline library is used
4. run new jobs including regression crons
-> jobs should be started successfully
5. Examine Manage Jenkins -> Configure Systemto presence of ZEBRUNNER_PIPELINE and ZEBRUNNER_VERSION global var. 
![image](https://user-images.githubusercontent.com/4551455/97764017-568d4600-1b1e-11eb-9255-375fe837f6ef.png)
6. Plus Modern SCM should be used to clone Zebrunner-CE library
![image](https://user-images.githubusercontent.com/4551455/97764048-6c027000-1b1e-11eb-9811-f572652ef78a.png)

**Comment by okamara** [comment]
Created a separate bug https://github.com/zebrunner/zebrunner/issues/337

**Comment by vdelendik** [comment]
@okamara we agreed to submit a new one aclose this one:)
Anyway adjusted upgrade steps. If you answer "n" about using custom global libraries or global choices migration task will replace by new valid items. Please re-test

**Comment by okamara** [comment]
Verified. Fixed.
