### ISSUE TITLE
remove github pull request checker plugin from default list

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#299]
after moving to generic webhook we can remove github pull request checker plugin and all configuration steps.
During removal need to find configuration steps for new generic webhook plugin if any. Ideally move the configuration onto the github part only.

related pipeline ticket: https://github.com/zebrunner/pipeline-ce/issues/5

**Comment by sandinosanchez** [comment]
delivered in #301, combined test cases will be publish in [#5](https://github.com/zebrunner/pipeline-ce/issues/5)

**Comment by okamara** [comment]
github pull request checker is removed. Verified on dev.
