### ISSUE TITLE
collect information about all items we generate on jenkins

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#302]
Globally we should start thinking about jenkins as a stateless service in zebrunner CE, i.e. we should have 0 credentuials, jobs, folder etc if possible.
So, please, collect information about all items we generate on jenkins for the organization.
for example:
- credentials for reporting
- folder for organization
- system jobs (one, two, tree)
- test jobs
-schedule for jobs

...

**Comment by okamara** [comment]
Jenkins - sign in credentials
Register organization - urls from Reporting
Pull request builder - ghprbhook-token
Jobs:
    Register Hub credentials
    QTestCredentials
    RegisterReportingCredentials
    RegisterTestRailCredentials
    RegisterUserCredentials
Credentials:
Sonarqube
AWS s3
Minio
Github pull request token
Selenium hub
Reporting service token, url

**Comment by vdelendik** [comment]
closing as info collected
