### ISSUE TITLE
install procps utility on jenkins-master

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#306]
It will be useful to have ps utility in jenkins-master image

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/jenkins-master/commit/77e67c2decbba85059c22353297beff896b9e448
during the test just connect into the jenkins-master container and run "ps" command:
`docker exec -ti jenkins-master bash
ps -ef`

ps should be installed and available for execution

**Comment by dhreben** [comment]
Verified
