### ISSUE TITLE
generate valid healthcheck script 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#307]
need valid internal helthcheck verification that jenkins is up&running. ideally get call to the servlte which return status

**Comment by vdelendik** [comment]
"#307" branch has draft implementation which should be adjusted to support secured jenkins verification

**Comment by vdelendik** [comment]
simple healthcheck script generated.
during the test setupzebrunner from develop branch and strat everything.
verify jenkins-master container status via `docker ps -a`
during stratup it should be `starting`, after startup - `healthy`

![image](https://user-images.githubusercontent.com/4551455/113279344-a3529400-92eb-11eb-9ea3-26880a5d5706.png)

**Comment by okamara** [comment]
Verified on latest develop version. Fixed.
<img width="252" alt="Снимок экрана 2021-04-01 в 14 05 42" src="https://user-images.githubusercontent.com/32964663/113285249-68545e80-92f3-11eb-9de7-7f86761c4420.png">
