### ISSUE TITLE
find a plugin which summarize queue job time

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#310]
we wanna to add extra plugins linke monitoring to track avg statistics of the master/slaves usage. One of the obligatory point - ability to summarize all waste time when jobs not executed in queue

**Comment by DimaGrinevich** [comment]
plugin: https://plugins.jenkins.io/cluster-stats/
statistics could be found at  Manage Jenkins » Cluster Statistics
example of output:
![Screenshot](https://user-images.githubusercontent.com/78387779/113122084-f52be900-921b-11eb-9e43-724463ed22fb.png)

**Comment by vdelendik** [comment]
cluster-stats doesn't summarize waste time. it has some avg stat which is not applicable for our purpose. also reviewed with negative results: https://plugins.jenkins.io/metrics/

**Comment by vdelendik** [comment]
closing as won't fix.
