### ISSUE TITLE
Bad credentials title for default jobs

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#311]
Steps:
1. Open Manage Jenkins
2. Manage Credentials
3. Verify that credentials title for default job is without "-" at the beginning
Actual result:
<img width="1091" alt="Screen Shot 2020-11-09 at 1 40 48 PM" src="https://user-images.githubusercontent.com/32964663/98531651-b1970980-2291-11eb-87b3-1919e20a5e79.png">
Expected:  Remove "-" from title at the beginning for default job

**Comment by vdelendik** [comment]
fixed. changes could be tested using "develop" branch of the zebrunnner

**Comment by dhreben** [comment]
Fixed.
