### ISSUE TITLE
jump to 1.1 jenkins-slaves

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#313]
1. jump to 1.1 beta slave images
https://github.com/zebrunner/jenkins-slave/issues/29
2. add "android" as default label to the existing slave
3. add independent slave in commented state with docker support as docker software was removed to minimize image size
https://github.com/zebrunner/jenkins-slave/issues/30

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/jenkins-master/commit/d6ac2e8a841079edd1d0c8697774875e6ba39d7c

changes covered items 1 and 3, i.e.:
1. inside ./jenkins/.env
TAG_JENKINS_SLAVE=1.1
2. inside ./jenkins/docker-composer.yml default jenkins-slave without docker label and commented slave with docker

**Comment by dhreben** [comment]
Verified.
<img width="1147" alt="Screenshot 2020-11-20 at 14 59 06" src="https://user-images.githubusercontent.com/50950954/99797830-04e64300-2b41-11eb-9f35-e09c9004cfcf.png">
