### ISSUE TITLE
scan all management jobs and replace scmURL by repoUrl

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#314]
all scmURL args should be renamed to repoUrl

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/jenkins-master/commit/6d71fdfe159bc37c91e0d5aed73ec8c04c5b1f59
only SmartJobsRerun was updated. changes are in zebrunner/zebrunner develop branch

**Comment by okamara** [comment]
Tested on dev.
TAG_JENKINS_MASTER=1.3-beta5
