### ISSUE TITLE
update Management_Jobs/* to use latest 1.3 pipeline version

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#315]
for now job uses develop branch of pipeline-ce library. before the release we have to update to use 1.3 pipeline release version and add job update into the patch/1.3.sh
Also default **RegisterRepository** should be updated to use 1.3 upcoming pipeline!

**Comment by vdelendik** [comment]
as part of the patch upgrade need replace also Management_Jobs/RegisterOrganization

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/jenkins-master/commit/d8f4b25b745c463cb71dc47cff67f25d6c23c8d9
after setup from zebrunner/zebrunner (develop branch) you should see that pipeline 1.3 is used in above management jobs
![image](https://user-images.githubusercontent.com/4551455/99971864-d7063600-2dae-11eb-904b-3581e56511fb.png)

**Comment by dhreben** [comment]
Verified on develop branch

<img width="687" alt="Screenshot 2020-11-24 at 02 12 26" src="https://user-images.githubusercontent.com/50950954/100025771-81577b00-2dfa-11eb-9982-8f7ac40ac123.png">
