### ISSUE TITLE
try to skip plugins bump up during upgrade 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#316]
Too many issues observed during hard update of plugins vs existing jenkins instance.
plugins.txt and extra_plugins.txt should be used only at the initial setup.

**Comment by vdelendik** [comment]
done. fully refactored plugins manipulations moving it onto the initial startup phase.

So globally:
1) replaced deprecated install-plugin.sh by jenkins-plugin-cli shell cript which define dependencies and conflicts much better
2) resolved existing conflicts in plugins.txt and bump up to the latest compatible versions
3) actual plugins download should happen only during first startup. i.e. after initial setup in jenkins-master logs we should see a lot of below messages and pretty slow start:
```
Installing plugins from plugins.txt...
Downloading plugin checks-api from url: https://updates.jenkins.io/download/plugins/checks-api/1.1.1/checks-api.hpi
Downloading plugin pipeline-maven from url: https://updates.jenkins.io/download/plugins/pipeline-maven/3.9.3/pipeline-maven.hpi
...
```
4) after initial setup we generate inside the jenkins-master `/var/jenkins_home/plugins.txt.installed` file which indicates that default plugins already installed
5) so 2nd etc restart should be much faster as they ignore manipulation with plugins
```
docker rm -f jenkins-master
./zebrunner.sh start
docker logs -f jenkins-master
**Zebrunner Jenkins plugins already installed.**
```

the same situation wuth custom extra_plugins.txt which can be shared in advance before initial start.

Changes are available in zebrunner/jenkins-master:1.3-beta2 (already pushed into zebrunner/zebrunner develop branch)

**Comment by vdelendik** [comment]
reopened as  downloading huge number of plugins too often is a problem so plugins.txt should be installed during image genearion as usual

**Comment by okamara** [comment]
Will be verified after fix https://github.com/zebrunner/zebrunner/issues/361

**Comment by okamara** [comment]
Verified.
