### ISSUE TITLE
qa: define test strategy for update plugins

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#317]
in 1.3 jenkins-master we did a jump
jenkins version 2.259 -> 2.267

also such plugins upgraded:
command-launcher:1.4 -> command-launcher:1.5
docker-workflow:1.24 -> docker-workflow:1.25
email-ext:2.77 -> email-ext:2.79
extensible-choice-parameter:1.6.0 -> extensible-choice-parameter:1.7.0
**generic-webhook-trigger:1.68 -> generic-webhook-trigger:1.72**
github:1.31.0 -> github:1.32.0
htmlpublisher:1.23 -> htmlpublisher:1.24
http_request:1.8.26 -> http_request:1.8.27
ldap:1.26 -> ldap:2.0
**slack:2.42 -> slack:2.44**
subversion:2.13.1 -> subversion:2.13.2
swarm:3.23 -> swarm:3.24
timestamper:1.11.5 -> timestamper:1.11.8

I highlighted the most risky from my point of view. So related functionality must be tested in advance!

**Comment by okamara** [comment]
I see docker-pipeline:1.25 instead of  docker-workflow:1.25

**Comment by okamara** [comment]
Tested on develop branch. Fixed.
