### ISSUE TITLE
Test run from Launcher is not visible in reporting Test runs

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#319]
Tested on ui: 1.14.0
server: 1.16.0.96-SNAPSHOT

Steps:
1. Jenkins is started
2. Organization and repo is created
3. Open Reporting
4. Run API demo test via Launcher
5. Open Test runs page and verify that test run is present
Actual result: test run is not present

**Comment by vdelendik** [comment]
repoURL hidden param for launcher and jobdsl should be updated to repoUrl

**Comment by okamara** [comment]
Verified. Fixed.
