### ISSUE TITLE
upgrade htmlpublisher plugin to 1.25

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#321]
1.24 htmlpublisher with 2.268 jenkins can't display published custom reports (carina, zafira etc).
need to upgrade it to show results

**Comment by vdelendik** [comment]
hotfix applied. major note!
before setup make sure to remove zebrunner/jenkins-master:1.3 image forcibly as it was reuploaded.

**Comment by dhreben** [comment]
Fixed.
<img width="1076" alt="Screenshot 2020-12-01 at 22 45 24" src="https://user-images.githubusercontent.com/50950954/100789006-eb89a480-3426-11eb-8ff5-1d2e983c452b.png">
