### ISSUE TITLE
Old url is present in Readme page (https://qaprosoft.github.io/qps-infra/)

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#324]
Steps:
1. Open page /jenkins/job/README.txt/
2. Click on url   Guide: https://qaprosoft.github.io/qps-infra/
Actual result: change old url to actual url https://qaprosoft.github.io/qps-infra/

**Comment by vdelendik** [comment]
fixed.
it should be tested using 1.4-beta1 jenkins-master

**Comment by okamara** [comment]
Not fixed.

**Comment by okamara** [comment]
Fixed.
