### ISSUE TITLE
remove embeddable-build-status plugin 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#329]
no need embeddable-build-status plugin in default set anymore

**Comment by vdelendik** [comment]
fixed. it should be tested in 1.4-beta1 jenkins-master.
after setup we shouldn't have such item in every job:
![image](https://user-images.githubusercontent.com/4551455/102425302-14f92180-401e-11eb-986d-8106f1478bc6.png)

**Comment by okamara** [comment]
Fixed.
