### ISSUE TITLE
Jenkins started too long and user had to restart/reinstall plugins 2-3 times

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#343]
Errors from h=jenkins-slave log:
Mar 11, 2021 10:14:23 AM hudson.plugins.swarm.Client run
SEVERE: RetryException occurred
hudson.plugins.swarm.RetryException: Failed to fetch slave info from Jenkins, HTTP response code: 503
	at hudson.plugins.swarm.SwarmClient.discoverFromMasterUrl(SwarmClient.java:151)
	at hudson.plugins.swarm.Client.run(Client.java:150)
	at hudson.plugins.swarm.Client.main(Client.java:128)
Mar 11, 2021 10:14:23 AM hudson.plugins.swarm.Client run

<img width="1436" alt="Screen Shot 2021-03-10 at 11 47 30 AM" src="https://user-images.githubusercontent.com/32964663/110775988-9b657e00-8270-11eb-8bc7-2d836c97c06e.png">

**Comment by vdelendik** [comment]
fixed downgrading to stable swarm plugin v3.24
jenkins original issue with 3.25 can be found here: https://issues.jenkins.io/browse/JENKINS-65119

**Comment by okamara** [comment]
Verified on Jenkins 2.286

**Comment by okamara** [comment]
<img width="690" alt="Снимок экрана 2021-04-01 в 18 46 05" src="https://user-images.githubusercontent.com/32964663/113319889-9600ce00-931a-11eb-82e3-908a2c69d0f9.png">
