### ISSUE TITLE
adjust default jenkins-slave labels

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#344]
For etails take a look to: https://github.com/zebrunner/pipeline-ce/issues/71
We have to remove such labels from [docker-compose.yml](https://github.com/zebrunner/jenkins-master/blob/d450f46ca459082b4fd2782fa9ad37c19a68e09f/docker-compose.yml#L27): 
api, web and maybe default as well

**Comment by vdelendik** [comment]
done: web and api labels removed from jenkins slave.
changes already applied to zebrunner, branch: develop

to test setup and start zebrunner from develop branch
-> jenkins-slave should be connected
-> jenkins-slave should have only such labels: default, gradle, maven and swarm

**Comment by dhreben** [comment]
Verified.

<img width="639" alt="Screenshot 2021-04-01 at 16 04 01" src="https://user-images.githubusercontent.com/50950954/113297893-e1f44880-9303-11eb-8d64-467a51b8891c.png">
