### ISSUE TITLE
2.283+ jenkins has incomplete setup wizard

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#345]
we have to finish setup wizard explicitly to be able to login without extra questions

https://github.com/jenkinsci/docker/issues/310

```
if (!instance.installState.isSetupComplete()) {
  println '--> Neutering SetupWizard'
  InstallState.INITIAL_SETUP_COMPLETED.initializeState()
}
```

**Comment by vdelendik** [comment]
fixed by generating such files during docker image build process:
```
RUN echo $JENKINS_VERSION > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state \
	&& echo $JENKINS_VERSION > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion
```
When files generated jenkins identify automatically that setup wizard not needed anymore.

during the test setup zebrunner from develop branchand login to jenkins
-> no questions about finishing setup process appears
-> you could login and see regular default folders

**Comment by dhreben** [comment]
Verified.
