### ISSUE TITLE
remove default sbt install

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#346]
w still don't have sbt pipeline code so this toll configuration can be skipped, i.e. remove `resources/init.groovy.d/configSbtAutoInstaller.groovy` groovy file

**Comment by vdelendik** [comment]
done. after setup zebrunner from develop branch make sure you have nothing in manaje jenkins -> global tools configuration -> sbt installations

**Comment by dhreben** [comment]
Test scenario:

1.Open Jenkins
2.Tap manaje jenkins
3.Tap global tools configuration

Actual result:   SBT installations is present in global tools configuration

<img width="710" alt="Screenshot 2021-04-01 at 17 19 37" src="https://user-images.githubusercontent.com/50950954/113308047-72378b00-930e-11eb-8166-74d1bad5ab49.png">

**Comment by vdelendik** [comment]
@dhreben closing again as in your screenshot no sbt available:)
that's a button to add new
