### ISSUE TITLE
Android and IOS-Demo-Tests  should not use  browser=chrome capabilities

### ISSUE THREAD

**Issue by dhreben** [zebrunner/jenkins-master#348]
Test scenario:

1.Open Jenkins
2.Tap Management_Jobs
3.Run RegisterOrganization
4.Run Mobile-Android-Demo-Test or Mobile-iOS-Demo-Test
5.Tap Console output

Actual result: Android and IOS-Demo-Tests  should not  use  browser=chrome capabilities

<img width="772" alt="Screenshot 2021-04-06 at 20 19 25" src="https://user-images.githubusercontent.com/50950954/113752223-63d5de80-9715-11eb-82c1-c8a42f5fe4ab.png">

**Comment by vdelendik** [comment]
fixed by changes in carina-demo

**Comment by dhreben** [comment]
Verified.
