### ISSUE TITLE
add Active Choices plugin by default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#349]
need it to support groups multi selection fields:
`uno-choice:2.5.6`

**Comment by vdelendik** [comment]
plugin added. moreover, obligatory upgrades done during 1.5 jenkins-master building.
to test shutdown old env and remove obligatory jenkins-master images as 1.5 was re-uploaded onto the hub docker.
1. login to jenkins
2. manage jenkins -> manage plugins -> installled
-> `Active Choices Plug-in` v2.5.6 should be preinstalled

**Comment by okamara** [comment]
Verified on dev. branch. Fixed.
<img width="928" alt="Снимок экрана 2021-06-18 в 13 17 53" src="https://user-images.githubusercontent.com/32964663/122546481-abdb8080-d037-11eb-9668-c26270f6c2c1.png">
