### ISSUE TITLE
made 1.5.2 pipelice-ce release as a default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#352]
make sure jenkins we provide for 1.8 release uses 1.5.2 pipeline-ce as minimal. we need these changes obligatory:
https://github.com/zebrunner/pipeline-ce/pull/162

**Comment by vdelendik** [comment]
done.
to test make sure to shutdown previos env and remove all jenkins-master docker images as 1.5 was re-uploaded to hub docker.
after the setup 
1. login to jenkins
2. manage jenkins -> configure system
-> ZEBRUNNER_VERSION should be 1.5.2 (maybe higher if new issues and fixes appear during regression testing)

**Comment by okamara** [comment]
Verified on dev. branch. Fixed.
