### ISSUE TITLE
Remove job SmartJobsRerun from Management_Jobs

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#354]
SmartJobsRerun no need now, as Milestones new feature will be instead of it.

**Comment by vdelendik** [comment]
done. setup zebrunner ce from develop branch and verify that no more `Management_Jobs/SmartJobsRerun` job

**Comment by dhreben** [comment]
Verified.

<img width="1118" alt="Screenshot 2021-07-15 at 12 20 38" src="https://user-images.githubusercontent.com/50950954/125769469-9a3aeb93-4995-4230-ac6a-f2d1eb1450ca.png">
