### ISSUE TITLE
remove RegisterQTestCredentials and RegisterTestRailCredentials jobs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#356]
no need such jobs anymore as integration moved to the reporting completely

**Comment by vdelendik** [comment]
done. setup zebtunner ce from develop branch and verif that no more such jobs among Management_Jobs

**Comment by dhreben** [comment]
Verified. 

<img width="1118" alt="Screenshot 2021-07-15 at 12 20 38" src="https://user-images.githubusercontent.com/50950954/125763914-9aac248f-c1d7-4591-b637-97d270dd24bb.png">
