### ISSUE TITLE
remove TCM credentials registration jobs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#357]
inside root Management_Jobs folder we don't need anymore:
* RegisterQTestCredentials
* RegisterTestRailCredentials

details can be found here: https://github.com/zebrunner/pipeline-ce/issues/175

**Comment by vdelendik** [comment]
jobs removed

**Comment by dhreben** [comment]
Verified.Jobs are removed.


![Screenshot 2021-09-10 at 13 29 42](https://user-images.githubusercontent.com/50950954/132840415-78d80449-8ad4-4ce5-9b88-f5940cd61112.png)
