### ISSUE TITLE
switch to released pipeline 1.7

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#366]
don't forget to switch to the 1.7 pipeline version before release.
https://github.com/zebrunner/jenkins-master/blob/05cd042901cfae54e1466a8c344bbbcdc60cdfe3/variables.env.original#L5

**Comment by vdelendik** [comment]
done. pipeline 1.7 released in advance: https://github.com/zebrunner/pipeline-ce/releases/tag/1.7

**Comment by dhreben** [comment]
Verified.
