### ISSUE TITLE
onPush job failed with new jobdsl plagin in Jenkins 

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#367]
Steps:
1. Set up zebrunner form develop branch 
2. Zebrunner version should be Develop
3. Register organization(pipeline version develop)
4. Register repo (pipeline version develop)
Actual result: onPush job failed 
Expected: onPush job is passed

**Comment by vdelendik** [comment]
fixed. adjusted list of plugins to keep jobdsl v1.77. please shutdown, remove and clone from scratch to get latest 1.8-beta2 jenkins image

**Comment by okamara** [comment]
verified on develop, fixed.
