### ISSUE TITLE
incorporate upgrade steps into the setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#372]
to move CE upgrade steps (https://github.com/zebrunner/community-edition/issues/491) into the sub-modules we have to support automatic detection of manual intervention inside variables.env for any value aka:
```
ADMIN_USER=admin
ADMIN_PASS=changeit
ROOT_EMAIL=qps-auto@qaprosoft.com
ADMIN_EMAILS=qps-auto@qaprosoft.com
JENKINS_MASTER_USERNAME=admin
JENKINS_MASTER_PASSWORD=changeit
JENKINS_OPTS=--prefix=/jenkins --httpPort=8080
JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Djava.awt.headless=true
```

**Comment by vdelendik** [comment]
done. it might be tested during upgrade and using syntenic steps below:

setup jenkins-master independently using branch develop (don't start services)
update variables.env putting non-default values for below vars, for example:
```
ADMIN_USER=admin1
ADMIN_PASS=changeit1
ROOT_EMAIL=qps-auto1@qaprosoft.com
ADMIN_EMAILS=qps-auto1@qaprosoft.com
JENKINS_MASTER_USERNAME=admin1
JENKINS_MASTER_PASSWORD=changeit1
JENKINS_OPTS="--prefix=/jenkins --httpPort=8080"
JAVA_OPTS="-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Djava.awt.headless=true"
```
start and do basic testing of availability of jenkins
run `./zebrunner.sh setup` again
-> all custom settings should be saved in variables.env!

**Comment by okamara** [comment]
Verified on development, fixed.
