### ISSUE TITLE
test upgrade to see if #381 require manual migration step

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#386]
https://github.com/zebrunner/jenkins-master/issues/381

potentially `master` label should beappended on every restart but let's test to see how it's going to upgrade to 2.0.

**Comment by vdelendik** [comment]
resolving to start testing.

**Comment by okamara** [comment]
The following scenario is not working any more:
1.setup jenkins-master independently using branch develop (don't start services)
2.update variables.env putting non-default values for below vars, for example:

ADMIN_USER=admin1
ADMIN_PASS=changeit1
ROOT_EMAIL=qps-auto1@qaprosoft.com
ADMIN_EMAILS=qps-auto1@qaprosoft.com
JENKINS_MASTER_USERNAME=admin1
JENKINS_MASTER_PASSWORD=changeit1
JENKINS_OPTS="--prefix=/jenkins --httpPort=8080"
JAVA_OPTS="-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Djava.awt.headless=true"
3.start and do basic testing of availability of jenkins
4.run ./zebrunner.sh setup again
-> all custom settings should be saved in variables.env!

Jenkins not started after these steps

**Comment by vdelendik** [comment]
@okamara you did something wrong. 
1. why did you update variables.env?
2. what's log do you have for jenkins-master docker container?

**Comment by okamara** [comment]
verified upgrade with correct steps, fixed.
1. old steps in test cases, will be updated
