### ISSUE TITLE
declare new SONAR_TOKEN global env var

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#388]
we need new variable for private sonar integration: SONAR_TOKEN.

For details visit:
https://github.com/zebrunner/sonarqube/releases/tag/1.4 and https://github.com/zebrunner/pipeline-ce/commit/e15f9dd44ea3712ae43d68b0453b233264cdc4cc

**Comment by vdelendik** [comment]
done. after setup CE from develop we should see new `SONAR_TOKEN` in manage jenkins -> configure system global variables. default value is empty for it.

**Comment by okamara** [comment]
Verified, fixed.
