### ISSUE TITLE
update managerial jobs to use `main` branch

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#390]
details: https://github.com/zebrunner/pipeline-ce/issues/301

**Comment by vdelendik** [comment]
done. all management_jobs should have as a pipeline version branch `main`, i.e.:
```
@Library('Zebrunner-CE@main')
```

**Comment by okamara** [comment]
Register Repository contains master -> @Library('Zebrunner-CE@master')

<img width="901" alt="Снимок экрана 2023-04-26 в 12 45 56" src="https://user-images.githubusercontent.com/32964663/234538303-a07a21d0-001c-4077-bb78-f7bbfbfb3806.png">

**Comment by okamara** [comment]
created separate ticket https://github.com/zebrunner/jenkins-master/issues/394
