### ISSUE TITLE
investigate an option to remove plugins updates logic

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#407]
for every new version of jenkins we prepare up-to-date obligatory plugins list.
let's try to avoid force update because it might corrupt preinstalled dependencies. As result after such kind of upgrades we hv o fix it manually.
still TBD howto provide obligatory list of required for the zebrunner plugins... How about making install operation at once and for upgrade only add manual step to sync with plugins

**Comment by azarouski** [comment]
PRs #409 #411
